### ISSUE TITLE
build scripts: Argument passing between build scrips is lame

### ISSUE THREAD

**Issue by lossius** [jamoma/Jamoma#130]
The top level (Jamoma) build script pass arguments in a lame way to build scripts for each submodule. Rather than passing on "development", "clean", "notest" and similar, it sends stuff like true and false.

In response the shared build script is parsing arguments expectign them to be in a fixed sequence.

This should be refactored so that we can pass arguments in the same way regardlesss of building everything, only core, or only one of the implementations, and the argument parsing should be a method in the shared library, so that we can make it DRY.

**Comment by tap** [comment]
obsolete issue due to cmake transition
